name: Publish pypi release

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: install requirements
        run: |
          python3 -m pip install -r requirements.txt

      - name: update python build tools
        run: |
          python3 -m pip install --user --upgrade setuptools wheel

      - name: build package
        run: |
          python3 setup.py sdist bdist_wheel

      - name: upload package
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASS: ${{ secrets.PYPI_PASS }}
        run: |
          python3 -m pip install --upgrade twine
          twine upload dist/* -u "$PYPI_USER" -p "$PYPI_PASS"